on:
  push:
    branches:
      - 3.0
name: Deploy
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@phpdocumentor'
      - uses: actions/checkout@master
      - name: Build
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          VERSION: '3.0'
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with:
          name: phpdocumentor/phpdoc.org/phpdoc.org
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          buildargs: VERSION,NODE_AUTH_TOKEN
          tags: '3.0'
        id: website_build
#      - name: 'deploy'
#        uses: jaapio/keelsh-deploy@1.0.0
#        with:
#          keelBaseUrl: ${{ secrets.KEEL_BASE_URL }}
#          image: 'docker.pkg.github.com/phpdocumentor/phpdocumentor/phpdoc.org'
#          tag: ${{ steps.docs_build.outputs.tag }}
